sudo: false
language: python
python: 3.4
cache: pip
install:
- ./setup_git_crypt.sh
- openssl aes-256-cbc -K $encrypted_c2bda3bb4472_key -iv $encrypted_c2bda3bb4472_iv -in git-crypt.key.enc -out git-crypt.key -d
- /tmp/git-crypt-master/git-crypt unlock ./git-crypt.key
- rm -rf git-crypt.key
- source env_vars && source env_vars.secret
- /tmp/git-crypt-master/git-crypt lock
- ./setup_aws_cli.sh
script:
- ./deploy_infra.sh
- ./update_cf_stack.sh
- ./create_cf_stack.sh
